# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version=1.21.10
	yarn_mappings=1.21.10+build.2
	loader_version=0.17.3
	loom_version=1.12-SNAPSHOT

# Mod Properties
	mod_version=0.3.3+wthit.1.21.5
	mod_id=reputation
	maven_group=atonkish.reputation
	archives_base_name=your-reputation

# Dependencies
	fabric_version=0.136.0+1.21.10
	wthit_version=17.3.2
	mod_menu_version=16.0.0-rc.1

# Distribution platform
	curseforge_id=1038047
	modrinth_id=1uiuiEVt
